# Generated by Django 5.1.1 on 2024-09-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='Creado', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedidoId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
