# Generated by Django 5.1.1 on 2024-09-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DireccionEnvio', '0001_manual_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionenvio',
            name='direccionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='distrito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
