    FROM python:3.11-slim

    RUN apt-get update && apt-get install -y \
        default-libmysqlclient-dev \
        build-essential \
        pkg-config \
        libmariadb-dev \
        libssl-dev \
        && rm -rf /var/lib/apt/lists/*

    WORKDIR /app

    COPY requirements.txt .
    RUN pip install --no-cache-dir -r requirements.txt

    COPY . .

    EXPOSE 8000

    CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
